### ISSUE TITLE
Pooling: Automatically delete ScratchOrg after failed creation

### ISSUE THREAD

**Issue by jverelst** [dxatscale/sfpowerkit#614]
### Issue description
We are gratefully using sfpowerkit to manage a pool of scratch orgs, and we have some Azure pipelines set up to continually fill the pool. However, every time we run the pipeline there are one or two Scratch Orgs that fail to create:

```
INFO [2021-12-24 14:47:10.918 +0000] (sfpowerkit): Creating Scratch  Org 4/10
Successfully created scratch org: 00D0E0000..... , username: test-......@example.com
INFO [2021-12-24 14:48:50.624 +0000] (sfpowerkit): Password successfully set for test-......@example.com
INFO [2021-12-24 14:48:50.625 +0000] (sfpowerkit): Creating Scratch  Org 5/10

=== Component Failures [1]
TYPE   FILE                                NAME        PROBLEM
─────  ──────────────────────────────────  ──────────  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error  shape/settings/Activities.settings  Activities  You can't use the Tooling API or Metadata API to enable or disable Shared Activities.  To enable this feature, visit the Activity Settings page in Setup.  To disable this feature, contact Salesforce.
ERROR running force:org:create:  Failed to deploy settings to scratch org.
INFO [2021-12-24 14:49:58.003 +0000] (sfpowerkit): Unable to provision scratch org  5 . Due to following Error: undefined
```

This happens at about 20% of the scratch orgs, which in itself is not really a problem because the next run of the pipeline will make sure that these are created anyway.

However: these failed scratch orgs are not deleted, so we end up with quite a few scratch orgs that are not put in a pull, but are still active. And since we use different pools for different uses, we don't know which pipeline created which failed scratch org, and if we may delete them (since some developers also create scratch orgs manually without a pooltag).

### Proposed solution
I could think of two possible ways that would work great for us:
- An optional flag in the pool config json, indicating that a scratchorg should be deleted if the creation fails
- A change in behavior, where an erroneous scratchorg is still put into the pool, but with a specific 'Error' status

Both would work, because in the 2nd scenario we can just quickly query all scratchorgs with status 'Error' and delete them with a pipeline too.

I hope this description is clear, and I am willing to provide a PR for either solution path.

**Comment by azlam-abdulsalam** [comment]
@henry88lay , This need to be fixed, failed scratch orgs should be deleted.

**Comment by henry88lay** [comment]
Hi @jverelst thanks for your patience I am doing my investigation into this ticket further. thank you for raising this issue :)

**Comment by azlam-abdulsalam** [comment]
@jverelst  Scratch Orgs failed at salesforce end do not return any details from the cli, it might get created in the backend and will use the limits, but it doesnt return a username or id. Hence we cant delete it.  This might need to raise an issue with sfdx-cli.

Thanks for the patience
