### ISSUE TITLE
Running all local tests in production

### ISSUE THREAD

**Issue by erick-bs** [dxatscale/sfpowerkit#626]
**Describe the bug**
I have a pipeline in a different environment-branches that use the command "sfdx sfpowerkit:org:destruct -m package/destructiveChanges.xml -u $MASTER_ORG_ALIAS" to deploy Destructive Changes and the command work very well, however in PRODUCTION I've realized that when we try to delete classes, triggers, the deployment run all tests locally and this it's terrible, because another components in the Destructive Change file it's not required to run all local tests. 

**To Reproduce**

1. sfdx sfpowerkit: "sfdx sfpowerkit:org:destruct -m package/destructiveChanges.xml -u $MASTER_ORG_ALIAS"

**Expected behavior**
Avoid to run any test, even less all test locally.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows/Linux]
- Node Version
- Version of sfpowerkit[e.g 1.45.0]
- Salesforce Org Version [ In case of pre release window ]

**Additional context**

**Comment by erick-bs** [comment]
Hi all! Good morning!
Do you have any update about it, please? Is there anything I can help or provide?

**Comment by Caitlyn-Mills** [comment]
Hi @erick-bs  we have made the decision to deprecate the org:destruct command and as such will not be pushing an enhancement for this issue. Thanks for raising. https://github.com/dxatscale/sfpowerkit/issues/722
