### ISSUE TITLE
📢 Deprecating org:manifest:build

### ISSUE THREAD

**Issue by azlam-abdulsalam** [dxatscale/sfpowerkit#644]
As of sfdx-cli 7.140.0,  force:source:manifest:create supports '-fromorg' flag. This is the same functionality as in org: manifest:build.  All the options except for exclude is available and could be raised as an addition to the cli command. Hence this command will be deprecated in future releases.

**Comment by Caitlyn-Mills** [comment]
We have deprecated this command in version 5.0.0
