### ISSUE TITLE
sfpowerkit:org:destruct should provide check and apex test options

### ISSUE THREAD

**Issue by MarcDBehr** [dxatscale/sfpowerkit#676]
**Is your feature request related to a problem? Please describe.**
The sfpowerkit:org:destruct command should provide access to the "-c" (check only) and "-l" (run tests) options (which would just be passed along)

**Describe the solution you'd like**
The ability to pass -c and -l to the destruct command

**Describe alternatives you've considered**
I can use force:source:deploy command with the -c and -l RunLocalTests, but then I also need to create the empty package.xml file  first

**Additional context**

**Comment by Caitlyn-Mills** [comment]
Thanks @MarcDBehr we will look into this.

**Comment by hassanalamibmx** [comment]
would also be very interesting to introduce the following options available in the `sfpowerkit:org:destruct`:

`-o | --ignoreerrors`
Optional
Ignores the deploy errors, and continues with the deploy operation. The default is false. Keep this parameter set to false when deploying to a production org. If set to true, components without errors are deployed, and components with errors are skipped.
> Type: boolean

`-g | --ignorewarnings`
Optional
If a warning occurs and ignoreWarnings is set to true, the success field in DeployMessage is true. When ignoreWarnings is set to false, success is set to false, and the warning is treated like an error.
> Type: boolean

**Comment by Caitlyn-Mills** [comment]
I am closing this issue, we have made the decision to deprecate sfpowerkit:org:destruct https://github.com/dxatscale/sfpowerkit/issues/722 
Thanks! Caitlyn
