### ISSUE TITLE
V4.2.10 - sfdxAuthUrl is missing in output when claiming an org from a pool

### ISSUE THREAD

**Issue by stoevie** [dxatscale/sfpowerkit#705]
**Describe the bug**
sfdxAuthUrl is missing in output of sfdx sfpowerkit:pool:fetch --tag pr_pool --json. This issue started today (V4.2.10)
V4.2.8 is working correct.

**To Reproduce**

1. sfdx plugins:install sfpowerkit
2. sfdx sfpowerkit:pool:fetch --tag pr_pool --json

**Expected behavior**
JSON output:
{
  "status": 0,
  "result": {
    "Id": "2SR69000000aaaaaa",
    "orgId": "00D1X000000bbbbb",
    "loginURL": "https://sample-page.salesforce.com/",
    "username": "test-doesnotexist@example.com",
    "password": "$secret",
    "expiryDate": "2022-07-08",
    "sfdxAuthUrl": "force://PlatformCLI::5Aep861sZkhY6e......................salesforce.com",
    "status": "Assigned"
  }
}

**Desktop (please complete the following information):**

-   OS: Windows
-   Node Version: v16.14.0
-   Version of sfpowerkit: 4.2.10
-   Salesforce Org Version : 55

**Comment by giri-uipath** [comment]
same here, started seeing this after CLI updated to 7.151.1

**Comment by azlam-abdulsalam** [comment]
Apologies, Pushing the fix in some time

**Comment by azlam-abdulsalam** [comment]
We have temporarily rolled back 4.2.10 to 4.2.8, while we identify a proper fix

**Comment by giri-uipath** [comment]
I can confirm it works now

**Comment by stoevie** [comment]
Yes, indeed, it's fixed. Thanks for your quick response.

**Comment by giri-uipath** [comment]
@azlam-abdulsalam seems like the issue has cropped up again
