### ISSUE TITLE
sfdx sfpowerkit:source:pmd Issue

### ISSUE THREAD

**Issue by AnjuGahlyan** [dxatscale/sfpowerkit#720]
While running sfdx sfpowerkit:source:pmd getting "Error: tunneling socket could not be established, statusCode=407"

**To Reproduce**
Execute sfdx sfpowerkit:source:pmd -d src/core-crm -o core-crm-pmd-output

1. sfdx sfpowerkit:source:pmd -d src/core-crm -o core-crm-pmd-output
![Uploading Socket_Error.png…]()

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [e.g. Windows/Linux]
-   Node Version
-   Version of sfpowerkit[e.g 1.45.0]
-   Salesforce Org Version [ In case of pre release window ]

**Additional context**

**Comment by Caitlyn-Mills** [comment]
Hi @AnjuGahlyan I believe this is a proxy error on your end. I am unable to replicate the issue. 

Thanks

**Comment by AnjuGahlyan** [comment]
Hi @ Caitlyn-Mills yes but afterr setting up proxy too it is not getting up resolved, SO can you please tell which proxy we need to set.

Thanks
