### ISSUE TITLE
📢 Deprecating org:destruct

### ISSUE THREAD

**Issue by azlam-abdulsalam** [dxatscale/sfpowerkit#722]
As sfdx source:delete and mdapi:deploy now supports deletion of metadata with pre/post as well as individual components. This command can be deprecated

**Comment by Caitlyn-Mills** [comment]
Hi @hassanalamibmx  you can supply a pre or post destructive change xml file with the force:source:deploy command: 
<img width="761" alt="image" src="https://user-images.githubusercontent.com/63215232/188338660-8e54fbf0-a416-467f-b0be-12bb6c93e06f.png">

Thanks!

**Comment by Caitlyn-Mills** [comment]
Hi @hassanalamibmx I understand the problem, since there are other avenues, such as creating an empty manifest in your repo, we will still be deprecating this command in the September release. You can still use the command in version 5.0.0 and below. 

Caitlyn
