### ISSUE TITLE
sfpowerkit merge command fails with error: profileObjFromServer.pageAccesses.filter is not a function

### ISSUE THREAD

**Issue by VertikaGoyal** [dxatscale/sfpowerkit#725]
**Bug Description**
sfdx sfpowerkit merge command fails with an error : TypeError: profileObjFromServer.pageAccesses.filter is not a function

**To Reproduce**
   
**Prerequisites:**
1. Ensure that your source has only 1 VF Page(Test) and your profile has access to this VF page only.
2. The destination should not have this VF page.

**Steps:**
1. Retrieve the full profile 
    sfdx sfpowerkit:source:profile:retrieve -n "Profile Test" -u source   
2. Reconcile the full profile against the destination
    sfdx sfpowerkit:source:profile:reconcile -n "Profile Test" -u destination  
4. Merge the permissions of the VF page with the reconciled profile
    sfdx sfpowerkit:source:profile:merge -n "Profile Test" -u source -m "ApexPage:Test"

**Expected behavior**
The permissions for the VF page should be merged without any error

**Screenshots**
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/46513126/186852820-cace931f-04cc-42c4-8979-544acfa115ea.png">

**Desktop**

-   OS: MacOS Monterey v12.1
-   Node Version: 14.17.3
-   Version of sfpowerkit[e.g 1.45.0]: 4.2.13
-   Salesforce Org Version [ In case of pre release window ] : 55.0

**Comment by Caitlyn-Mills** [comment]
@genoud  are you able to take a look at this one?
