### ISSUE TITLE
Getting text 'Config folder does not exists, Creating Folder' with --json param

### ISSUE THREAD

**Issue by VertikaGoyal** [dxatscale/sfpowerkit#744]
**Describe the bug**
When using the command sfdx sfpowerkit:source:profile:retrieve -u <alias> -n <profilelist> --json in a respository without .sfdx/sfpowerkit directory, the string 'Config folder does not exists, Creating Folder' is concatenated along with the json response.

**To Reproduce**

1. In a repository without .sfdx/sfpowerkit folder, run the command **sfdx sfpowerkit:source:profile:retrieve -u <alias> -n <profilelist> --json**

2. **Expected behavior**
A json response of the following kind:
 ```
{
  "status": 0,
  "result": [
    {
      "state": "Updated",
      "fullName": "MergeDX",
      "type": "Profile",
      "path": "my-app/main/default/profiles/MergeDX.profile-meta.xml"
    }
  ]
}

```

**Actual:**
```
Config folder does not exists, Creating Folder
Number of profiles to retrieve 1
{
  "status": 0,
  "result": [
    {
      "state": "Updated",
      "fullName": "MergeDX",
      "type": "Profile",
      "path": "my-app/main/default/profiles/MergeDX.profile-meta.xml"
    }
  ]
}

```
**Desktop :**

-   OS: Mac
-   Node Version : v14.17.3
-   Version of sfpowerkit : v5.0.0
-   Salesforce Org Version: 56.0

**Additional Context:** 
We depend on the json response to parse and provide info necessary to the end user and hence necessarily need only a  json response  with --json param

**Comment by azlam-abdulsalam** [comment]
Thanks @VertikaGoyal . Will look into this.

**Comment by VertikaGoyal** [comment]
Hi @azlam-abdulsalam 
I have looked into the fix and I'll provide an MR for the same if it can help!

**Comment by VertikaGoyal** [comment]
Hi @azlam-abdulsalam, please check if we can use [this](https://github.com/dxatscale/sfpowerkit/pull/745) MR for the fix.
Thanks :D

**Comment by azlam-abdulsalam** [comment]
Fixed in November 22 release
