### ISSUE TITLE
Issue while running sfpowerkit plugin in jenkins run time

### ISSUE THREAD

**Issue by sairohith1009** [dxatscale/sfpowerkit#751]
Hi,

after installing SFpower kit in run time, the plugin is able to compare two commit i'ds and generate delta package. But sometimes the Package.xml from the folder is getting copied to this delta package and sometimes package.xml is not getting copied and the end the Jenkins Job is getting failed.

In the below image the Package.xml got copied from git to delta package and the validation went successful
<img width="622" alt="2" src="https://user-images.githubusercontent.com/95403728/212660153-1e2878f2-9102-4583-92a2-935bd3eec55c.png">

in the below logs the jenkins job is not able to copy the Package.xml
<img width="620" alt="1 (1)" src="https://user-images.githubusercontent.com/95403728/212659542-0ab3b0ce-c8b3-483f-834e-5cc756e93b86.png">

and the out put for the above build was as shown below
<img width="371" alt="3 (1)" src="https://user-images.githubusercontent.com/95403728/212660264-44cc5a0c-f6b2-40c3-9955-8d1e995f4b6c.png">

Need some solution here.

Thanks in advance.

**Comment by azlam-abdulsalam** [comment]
@sairohith1009  sfpowerkit project:diff is being deprecated, there is no active work on this. Recommed to use sgd-delta for diff based deployment
