### ISSUE TITLE
Scratch org pool source deploy

### ISSUE THREAD

**Issue by MeStrak** [dxatscale/sfpowerkit#755]
**Is your feature request related to a problem? Please describe.**

Source deployment to a scratch org in our CI pipeline takes 12+ minutes, and it is a bottleneck in our overall CICD process. Pooling will save a few minutes of package installation but from what I understand doesn't allow source deployment (and even if it did this would time out for us with the 6 minute timeout).

**Describe the solution you'd like**

- I would like to be able to deploy source to the scratch org for a given git hash so that in the CI pipeline I can use sfdx-git-delta to only deploy the code that changed, saving quite a lot of time.
- One idea I thought of would be to have a way of staging orgs in the pool, so once built they could be transferred to another pool where source could be deployed to them.
- We would also need a way to know the git hash/tag used for deploying the source to the scratch org which is allocated from the pool to run through sfdx-git-delta.

**Describe alternatives you've considered**

Looked at Salesforce snapshots but it's still a pilot, basic and poorly documented.

**Additional context**

-

**Comment by vuha-acn** [comment]
@MeStrak - Have you explore using the [Package Checkpoints](https://docs.dxatscale.io/sfpowerscripts/prepare#using-prepare-in-multiple-stages) yet for your prepare of scratch org pools?  You can use the snapshotPool flag to do this.  Also, can you please elaborate on your source deployment? How many source packages do you have or is it a singular force-app?  By default, scratch org pools will be deployed using source deploy for the packages.  What is also limiting your 6 minute timeout in your runner/agents?

**Comment by MeStrak** [comment]
Thanks for the fast reply! So ... I think I've been stupid and misread the docs. I was sure I read that there was a 6 minute limit to a build, but checking again today the only reference I can see to 6 minutes is the default wait time.

We have a few packages which are installed in CI, but all code is currently in a single force app - that's the 12 minute part.

Given the references you sent and the fact that I misread the limit, it looks like it is possible to do what I want. I'm gonna close this for now to avoid confusion and if I run into any issues I'll open another.

Thanks!
